services:
  scan_cordova:
    build: .
    container_name: scan_cordova
    hostname: scan_cordova
    restart: always
    #env_file: .env
#    user: scan
    working_dir: /root/ScanApp
    ports:
      - "8000:8000"
    volumes:
      - ./ssh:/home/scan/.ssh
      - ./:/root/ScanApp
    command: "sleep infinity"
