#!/bin/bash
clear \
&& cordova platform remove android \
&& cordova plugin add https://github.com/fluxguide/cordova-plugin-qr-barcode-scanner/tree/58fed73a7c6e306a0a9fef3fe4586706e9b73a33 \
&& cordova plugin add cordova-plugin-advanced-http \
&& cordova platform add android@14.0.0 \
&& cordova build android
